FROM eclipse-temurin:17-jdk
LABEL maintainer="test_user@gmail.com"
EXPOSE 8080
COPY target/SpringBoot-Aws-Sqs-docker-1.0.jar SpringBoot-Aws-Sqs-docker-1.0.jar
ENTRYPOINT ["java","-jar","/SpringBoot-Aws-Sqs-docker-1.0.jar"]