#spring.application.name=SpringBoot-Aws-Sqs
#server.port=8080

#swagger.api-docs.enabled=true
#swagger.ui.enabled=true
#swagger.ui.path=/swagger-ui.html
#swagger.api-docs.path=/v3/api-docs
#swagger.api-docs.title=SpringBoot-Aws-Sqs



#accessKey=dummyAccessKey
#secretKey=dummySecretKey
#sqs.url=your-sqs-queue-url

region=ap-south-1
cloud.aws.region.static=ap-south-1
cloud.aws.region.auto=false
cloud.aws.stack.auto=false
spring.main.allow-bean-definition-overriding=true
logging.level.com.amazonaws.util.EC2MetadataUtils=error
logging.level.com.amazonaws.internal.InstanceMetadataServiceResourceFetcher=error


